### ISSUE TITLE
How to import WmsMapType from unpkg or jsdelivr CDN?

### ISSUE THREAD

**Issue by thexs-dev** [googlemaps/js-ogc#370]
It's likely a trivial question, but no idea on the answer

How to import WmsMapType from unpkg or jsdelivr CDN?

I am trying as follows

`import { WmsMapType } from 'https://cdn.jsdelivr.net/npm/@googlemaps/ogc@1.0/dist/index.esm.js';`

But I am getting an error due to the dependencies
`Uncaught (in promise) TypeError: Failed to resolve module specifier "query-string". Relative references must start with either "/", "./", or "../"`

Is there anyway to achieve this?

Thanks in advance

**Comment by jpoehnelt** [comment]
Something like this should work.

```html
<script src="https://unpkg.com/@googlemaps/ogc@1.0.26/dist/index.min.js"></script>
<script>
  // Google Maps JS API must also be loaded
  new google.maps.plugins.ogc. WmsMapType(...)
</script>
```

**Comment by thexs-dev** [comment]
Still getting a similar queryString error as follows
`Uncaught ReferenceError: queryString is not defined
    at index.min.js:1:13689`
Any other way to avoid this problem?

**Comment by jpoehnelt** [comment]
I'll just switch to the built-in `URL` object now that support is better instead of query-string.

**Comment by jpoehnelt** [comment]
The new version which will be published in a couple minutes shouldn't have that dependency.
